<?php

$source = array(
"m,cielo,hanaq pacha",
"m,fuego,nina",
"m,agua,unu",
"m,viento,wayra",
"f,tierra,allpa",
"f,vida,kawsay",
"m,arbol,mallki",
"m,cerro,urqu",
"m,valle,q'uñijallp'a",
"f,flor,t'ika",
"f,piedra,rumi",
"m,corazón,sunqu",
"m,amor,khuyay",
"f,felicidad,kusisami",
//"m,sol,inti",
"f,luna,killa",
"f,estrella,ch'aska",
"m,caballo,uywa",
"f,mariposa,pillpa",
"f,vicuña,wari ",
"f,alpaca,paqu",
"f,raiz,saphi",
"f,semilla,muqu",
"f,laguna,qhucha",
"m,río,mayu",
//"f,lluvia,Para",
"f,llovizna,chirapa",
"m,baile,tusuy",
"f,fiesta,raymi",
"m,sueño,musquy",
"m,camino,ñan",
"f,calle,kikllu",
"m,hombre,qhari",
"f,mujer,warmi",
"f,casa,wasi",
"f,puerta,punku",
"f,asiento,tiyana",
"f,cama,puñuna",
"f,mesa,hamp'ara",
"f,pared,pirqa",
"f,sangre,yawar",
"f,fuerza,kallpa",
"f,sal,kachi",
"f,mundo,t'iqsimuyu",
"f,arena,aqu",
"f,ladera,qhata",
"m,manantial,pukyu",
"f,peña,qaqa",
"f,catarata,paqcha",
"m,volcán,are",
"m,rocío,chhulla",
"m,arco iris,k'uychi",
"m,granizo,chikchi",
"f,garua,iphu",
"m,relámpago,illapa",
"m,frio,chiri",
"m,calor,q'uñi",
"f,noche,tuta",
"m,día,p'unchaw",
"f,selva,yunka",

// SEMANA
"m,domingo,intichay",
"m,lunes,killachay",
"m,martes,antichay",
"m,miércoles,quyllurchay",
"m,jueves,illapachay",
"m,viernes,ch'askachay",
"m,sábado,k'uychichay",

// COLORES
"m,color,llimp'i",
"m,rojo,puka",
"m,verde,q'umir",
"m,azul,anqas",
"m,blanco,yuraq",
"m,negro,yana",
"m,gris,uqi",
"m,castaño,ch'umpi",
"m,morado,kulli",
"m,rosado,panti",
"m,amarillo,q'illu",
"m,moteado,ch'iqchi",

//CUERPO
"f,cabeza,uma",
"m,cabello,chukcha",
"f,cara,uya",
"m,ojo,ñawi",
"f,pestaña,qhichipra",
"f,ceja,qhiñipa",
"f,nariz,sinqa",
"f,boca,simi",
"m,labio superior,sirphi",
"m,labio inferior,wirp'a",
"m,diente,kiru",
"f,lengua,qallu",
"m,cuello,kunka",

"m,tronco,kurku",
"m,pecho,qhasqu",
"m,estómago,wiksa",
"f,cintura,wiqaw",
"f,cadera,t'iqni",

"m,hombro,rikra",
"m,brazo,mak'a",
"m,codo,kukuchu",
"f,mano,maki",
"f,palma,maki qucha",
"m,dedo,rukana",
"f,uña,sillu",

"m,muslo,rakhu chaka",
"f,pierna,chaka",
"f,rodilla,qunquri",
"m,pie,chaki",

// VERBOS
"m,lavar (cara),upay",
"m,lavar (cabello y ropa),t´aqsay",
"m,lavar (boca y dientes),muqch´iy",
"m,lavar,maqchiy",
"m,cocinar,wayk´uy",
"m,comer,mikuy",
"m,beber,upyay",
"m,cortar,kuchuy",
"m,mover,kuyuy",
"m,llorar,waqay",
"m,cantar,takiy",
"m,bailar,tusuy",
"m,mirar,qhaway",
"m,llamar,waqhay",
"m,dormir,puñuy",
"m,hablar,rimay",
"m,escribir,qillqay",
"m,trabajar,llamk´ay",
"m,descansar,samay",
"m,caminar,puriy",
"m,subir,wichay",
"m,bajar,uray",
"m,sentar,tiyay",
"m,parar,sayay",
"m,sacar,hurquy",
"m,meter,winay",
"m,ir,riy",
"m,venir,hamuy",
"m,dar,quy",
"m,entrar,haykuy",
"m,salir,lluqsiy",
"m,abrir,kichay",
"m,cerrar,wisqay",
"m,nacer,paqariy",
"m,morir,wañuy",
"m,levantar,hatariy",
"m,hechar,kumpay",
"m,florecer,t´ikariy",
"m,volar,phaway",
);
?>

